name: posture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.13
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  flutter_timezone: ^4.1.1
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
